version: 2
updates:
- package-ecosystem: "pip"
  directory: "scripts/"
  schedule:
    interval: "weekly"
- package-ecosystem: "pip"
  directory: "fdmlpy/"
  schedule:
    interval: "weekly"
- package-ecosystem: "pip"
  directory: "fdml-gui/"
  schedule:
    interval: "weekly"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
