from typing import Iterator, overload
import numpy as np

class Locator():
  def __init__(self) -> None: ...
  def init(self, pwh: Polygon_with_holes) -> None: ...
  def query1(self, d: FT) -> list: ...
  def query2(self, d1: FT, d2: FT) -> list: ...
