function [] = print_coeffs(fid, sol)
  syms d1 d2 k m2 real
  A1 = reduceRedundancies([sol.A1], [d1, d2, k, m2])
  fprintf(fid, 'A1 = %s\n', char(A1))
  B1 = reduceRedundancies([sol.B1], [d1, d2, k, m2])
  fprintf(fid, 'B1 = %s\n', char(B1))
  C1 = reduceRedundancies([sol.C1], [d1, d2, k, m2])
  fprintf(fid, 'C1 = %s\n', char(C1))
  D1 = reduceRedundancies([sol.D1], [d1, d2, k, m2])
  fprintf(fid, 'D1 = %s\n', char(D1))

  fprintf(fid, '\n')
  A2 = reduceRedundancies([sol.A2], [d1, d2, k, m2])
  fprintf(fid, 'A2 = %s\n', char(A2))
  B2 = reduceRedundancies([sol.B2], [d1, d2, k, m2])
  fprintf(fid, 'B2 = %s\n', char(B2))
  C2 = reduceRedundancies([sol.C2], [d1, d2, k, m2])
  fprintf(fid, 'C2 = %s\n', char(C2))
  D2 = reduceRedundancies([sol.D2], [d1, d2, k, m2])
  fprintf(fid, 'D2 = %s\n', char(D2))
end
